### ISSUE TITLE
TODO/FIXME Count 1

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/webkms-client#12]
- [ ] TODO: should `delete` be used here as a separate action?
       Commit: (cf1ed92) Support keystores and other new API changes.
       File:  [KmsClient.js:567](https://github.com/digitalbazaar/webkms-client/blob/master/KmsClient.js#L567)
       Dave Longley commented a year ago

**Comment by dlongley** [comment]
Addressed, closing.
