### ISSUE TITLE
crypto-ld is in devDependencies instead of dependencies

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/webkms-client#16]
In `CapabilityAgent.js`, `crypto-ld` is imported and used. However, in `package.json`, it's in devDependencies (rather than regular `dependencies`). 
As a result, when it's used as an npm dependency downstream, the import fails. (I suspect we haven't run into this problem previously because downstream libraries that have used it so far _also_ had their own `crypto-ld` dep.)

**Comment by davidlehn** [comment]
@dmitrizagidulin Docs on auto-close syntax to use in PRs: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by dmitrizagidulin** [comment]
Thanks @davidlehn!
