### ISSUE TITLE
Add link to the web-kms spec

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/webkms-client#3]
Trying to find the documentation necessary to use Web KMS with Azure, Google or Amazon.

**Comment by dmitrizagidulin** [comment]
@OR13 Thanks. We're right in the middle of writing up the spec - we just created a repo for it over at https://github.com/digitalbazaar/webkms, and content incoming.

**Comment by mandyvenables** [comment]
@OR13 Does this documentation answer your questions? https://github.com/w3c-ccg/webkms
If so please close the issue.

**Comment by OR13** [comment]
@mandyvenables If this PR is merged, this issue can be safely closed imo: https://github.com/digitalbazaar/webkms-client/pull/14

**Comment by mattcollier** [comment]
PR Merged, closing.
