### ISSUE TITLE
No affirmative response from the `revokeCapability` API

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/webkms-client#34]
https://github.com/digitalbazaar/webkms-client/blame/f9bb1930c266ff3b5b45e53e730f7f4fb1ae36db/KmsClient.js#L162-L206

@dlongley you and I have both worked on this API and evidently thought at one time that it was OK to just return `undefined` here on success.  Seems very unusual.  Was there some design consideration here that would prohibit a response of `{success: true}` or the like.

We are debugging issues related to this API downstream and the lack of an affirmative response is adding to the difficulties.

**Comment by mattcollier** [comment]
Here we have an instance where the backend API returns `{success: true}` and is relayed by `return response.data`: 

https://github.com/digitalbazaar/webkms-client/blob/f9bb1930c266ff3b5b45e53e730f7f4fb1ae36db/KmsClient.js#L568

We assert on this value here:
https://github.com/digitalbazaar/bedrock-kms-http/blob/dce68f4e311949662b048acd459f16da6f678e3d/test/mocha/21-revocation-ip-allow-list.js#L194-L195

**Comment by dlongley** [comment]
@mattcollier,

> We are debugging issues related to this API downstream and the lack of an affirmative response is adding to the difficulties.

Can you say more about these difficulties? For example, why would returning a value of `{success: true}` be better than checking for the presence of an exception? I'd rather not add a return value if we don't need one.

**Comment by dlongley** [comment]
@mattcollier,

> Here we have an instance where the backend API returns {success: true} and is relayed by return result.data

If that's returning `{success: true}`, it sounds like there's a bug. It should be returning the config (per the docs).

**Comment by dlongley** [comment]
Closing per discussion as won't fix.
