### ISSUE TITLE
Use `globalThis`.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/webkms-client#39]
`lib/SeedCache.js` uses `window` to access `localStorage`.  Can/should that be converted to use `globalThis`?

See also: https://github.com/digitalbazaar/webkms-client/issues/30

**Comment by dlongley** [comment]
I'd say leave it be for now -- because we probably intend to remove it entirely.

**Comment by dlongley** [comment]
But.. if it's an issue and it continues to work just fine, sure.

**Comment by dlongley** [comment]
`SeedCache` has been removed, closing.
