### ISSUE TITLE
Somehow bind KMS client to ControllerKey instance

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/webkms-client#5]
I encountered this syntax in a relying module:
```
    const keyDesc = await controllerKey.kmsClient.getKeyDescription(
      {keyId: zcapKey.id, invocationSigner: controllerKey});
```

Seemed strange to me to be passing `controllerKey` into what would be considered a class method of `controllerKey`.  

Would it be appropriate to instantiate a KmsClient with an invocationSigner that it will use for all its operations?

https://github.com/digitalbazaar/webkms-client/blob/master/KmsClient.js#L28

**Comment by dlongley** [comment]
`controllerKey` is no longer a thing and its replacement (`capabilityAgent`) doesn't have a `kmsClient` member, closing.
