### ISSUE TITLE
Do not throw Axios errors

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/webkms-client#9]
https://github.com/digitalbazaar/webkms-client/blob/refactor/KmsClient.js#L344

And elsewhere.

Called from `AsymmetricKey.sign` here: https://github.com/digitalbazaar/webkms-client/blob/master/AsymmetricKey.js#L53

When `jsonld-signatures.sign` is called using an `AsymmetricKey` instance and a `NotAllowedError` is returned (for instance), a monstrous Axios error is returned.  

Axios errors in the kmsclient API should be wrapped as elsewhere.

**Comment by mandyvenables** [comment]
This will be resolved by the move away from axios.

**Comment by mattcollier** [comment]
axios was removed as a dependency in v2.2.0: https://github.com/digitalbazaar/webkms-client/blob/master/CHANGELOG.md#220---2020-06-19

closing.
